### ISSUE TITLE
Unable to play to group because of "Please check that all remotes in the group are online" error

### ISSUE THREAD

**Issue by PureTryOut** [MayaPosch/NymphCast#80] opened 2023-04-14 20:07 UTC
Both servers present are online and can play audio just fine when send to it individually, just not through a group.

**Comment by MayaPosch** [comment] 2023-04-17 19:12
Reproduced the issue, will have a look at it.

**Comment by MayaPosch** [comment] 2023-04-18 10:02
Interesting symptoms so far: it works with the slave remote in a local VM (bridged networking), but I get the error when the slave remote is on dedicated hardware (Raspberry Pi Zero W). Since everything in this failing configuration uses WiFi, I'm leaning towards a time-out issue, but will keep investigating.

**Comment by PureTryOut** [comment] 2023-04-18 11:23
I'm also doing it over Wi-Fi so that seems plausible :thinking:

**Comment by MayaPosch** [comment] 2023-04-18 11:59
The problem appears to be the auto-detected IP addresses in the list of slave remotes that get handed to the master remote. I had the multi-room playback working just fine earlier on the aforementioned Raspberry Pi Zero W, in sync with the master remote on the Win10 laptop, all via WiFi.

Looking at the previous non-working playback attempt on these devices, here the Win10 laptop's IP was the VirtualBox virtual IP address (host-only network), while the Raspberry Pi Zero W's IP was that of the WiFi network.Obviously, if the Win10 laptop is the master in this scenario, it can use the RPi0W as slave, but vice versa does not work, since the VBox host-only network is not accessible from the RPi0W.

Theoretically, this is a scenario that should not occur when e.g. running the Player on another system on the (WiFi) network, but which can be problematic when running the Player on the same system as one of the group remotes. A possible solution here would be to keep track of the different IPs per server remote, and match them up per network range when put into a group. Though that may backfire in other fun ways.

This may take some thought :)

**Comment by MayaPosch** [comment] 2023-04-28 19:16
It would definitely be an issue whenever using the client on the same system as a remote that's part of a group, yes.

I'm still looking at an elegant solution for this that covers all cases. Incidentally it's also a potential issue with the NymphCast MediaServer when it runs on the same system as a remote, though that should be an uncommon issue outside of testing. Still, good to tackle that one at the same time :)

**Comment by MayaPosch** [comment] 2023-05-02 12:32
I have implemented a change in the Group dialogue. This should keep a local remote (hostname == local hostname) always as the first item in the first position of the list, and thus as the master remote.

Currently it only checks for this when creating a new group or when adding a new remote to a group, which seems sufficient to me, but feel free to think of further use cases :)

**Comment by MayaPosch** [comment] 2024-03-26 20:11
Closing this issue as complete. Feel free to reopen or create new issue as needed.

**Closed by MayaPosch** 2024-03-26 20:11 UTC
Labels: bug
