### ISSUE TITLE
Errors on Server Launch

### ISSUE THREAD

**Issue by Arndorferd** [MayaPosch/NymphCast#37] opened 2021-03-16 18:34 UTC
Getting these errors when I launch the server. It does still run but videos crash often.

Starting NyanSD on port 4004 UDP...
 (0, 0) : ERR  : Failed in call to function 'RegisterGlobalFunction' with 'bool performHttpQuery(string, string &out)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterGlobalFunction' with 'bool performHttpsQuery(string, string &out)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterGlobalFunction' with 'void clientSend(int, string)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterGlobalFunction' with 'bool streamTrack(string)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterGlobalFunction' with 'bool readValue(string, string &out, uint64)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterGlobalFunction' with 'bool storeValue(string, string &in)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectBehaviour' with 'JSONValue' and 'void f()' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectBehaviour' with 'JSONValue' and 'void f(bool)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectBehaviour' with 'JSONValue' and 'void f(int)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectBehaviour' with 'JSONValue' and 'void f(uint)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectBehaviour' with 'JSONValue' and 'void f(float)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectBehaviour' with 'JSONValue' and 'void f(double)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectBehaviour' with 'JSONValue' and 'void f(const string&in)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectBehaviour' with 'JSONValue' and 'void f(const JSONValue&in)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectBehaviour' with 'JSONValue' and 'void f()' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'JSONValue& opAssign(bool)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'JSONValue& opAssign(int)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'JSONValue& opAssign(uint)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'JSONValue& opAssign(float)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'JSONValue& opAssign(double)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'JSONValue& opAssign(const string&in)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'JSONValue& opAssign(const JSONValue&in)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'JSONValueType get_valueType() const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'JSONNumberType get_numberType() const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'string get_valueTypeName() const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'string get_numberTypeName() const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'bool get_isNull() const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'bool get_isBool() const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'bool get_isNumber() const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'bool get_isString() const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'bool get_isArray() const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'bool get_isObject() const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'bool getBool(bool defaultValue = false) const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'int getInt(int defaultValue = 0) const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'uint getUInt(uint defaultValue = 0) const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'float getFloat(float defaultValue = 0) const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'double getDouble(double defaultValue = 0) const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'const string getString(const string&in defaultValue = string()) const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'JSONValue opIndex(uint)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'const JSONValue& opIndex(uint) const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'void Push(const JSONValue&in)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'void Pop()' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'void Insert(uint, const JSONValue&in)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'void Erase(uint, uint length = 1)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'void Resize(uint)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'uint get_size() const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'JSONValue& opIndex(const string&in)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'const JSONValue& opIndex(const string&in) const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'void Set(const string&in, const JSONValue&in)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'JSONValue get(string&in)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'void Erase(const string&in)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'bool Contains(const string&in) const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONValue' and 'void Clear()' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONFile' and 'bool fromString(const string&in)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONFile' and 'string toString(const string&in = string("	")) const' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONFile' and 'JSONValue& getRoot()' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'JSONFile' and 'JSONValue& get_root()' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectBehaviour' with 'JSONFile' and 'void f()' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectBehaviour' with 'JSONFile' and 'void f()' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectBehaviour' with 'RegExp' and 'void f()' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectBehaviour' with 'RegExp' and 'void f()' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'RegExp' and 'void createRegExp(string &in)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'RegExp' and 'int extract(string &in, string &out, int = 0)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'RegExp' and 'int extract(string &in, int offset, string &out, int = 0)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'RegExp' and 'int findall(const string &in, array<string> @+ = null)' (Code: asNOT_SUPPORTED, -7)
 (0, 0) : ERR  : Failed in call to function 'RegisterObjectMethod' with 'RegExp' and 'int findfirst(const string &in, string &out)' (Code: asNOT_SUPPORTED, -7)

**Comment by MayaPosch** [comment] 2021-03-17 11:08
Those errors are from the AngelScript runtime from what are apparently template-related issues.

To better understand and replicate the issue if possible, I'd need to know the platform and toolchain used for compiling. Could you provide those?

**Comment by Arndorferd** [comment] 2021-03-17 13:13
Im using  2020-08-20-raspios-buster-arm64, found here [Rasbian 64bit](https://downloads.raspberrypi.org/raspios_arm64/images/), which is a 64 bit arm Debian based package, this is running on a 64 bit quad core Cortex-A72. My client is on 64 bit Ubuntu based PopOS running amd-64. If you could tell me how to find out that information on the compiler. Should I just look at the logs during compilation?

**Comment by MayaPosch** [comment] 2021-03-29 10:16
I have managed to replicate the issue on Ubuntu 21.10 on a Raspberry Pi 4 system. 

* The issue appears to be related to the template specialisation code in the AngelScript library: https://www.gamedev.net/forums/topic/662414-issue-in-registering-template-specialization/
* The effect is that the registration of custom AngelScript functions and types fails, and presumably that the AngelScript-based apps thus no longer work.

So far it only seems to occur on ARM64 (AArch64) with a 64-bit OS, but not on AMD64 systems. Next step is figuring out what causes this exact issue, and whether it is due to how the AS library is being compiled, or some other cause.

**Comment by MayaPosch** [comment] 2021-03-29 11:18
Apparently AArch64 support was only added recently: https://www.gamedev.net/forums/topic/707084-has-anyone-compiled-angelscript-on-aarch64/

I'll update AngelScript to the current version and retest.

**Comment by MayaPosch** [comment] 2021-04-01 10:14
Confirmed that this issue has now been fixed on Ubuntu for AArch64 with the new AngelScript runtime.

Two source files were missing from the list in the Makefile. These have been added. After this the NymphCast server starts up and runs normally, with no AS-related errors or warnings.

Closing this issue. Feel free to open a new issue if there are any further issues.

**Closed by MayaPosch** 2021-04-01 10:14 UTC
